import type { Channel, ChannelMember } from "@/modules/chat/interfaces/channels/channel.interface";
import type { Message } from "@/modules/chat/interfaces/message.interface";
import type { User } from "@/modules/auth/interfaces/user.interface";

// ─── Mock Users ──────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: "u1",
    username: "Lucía",
    email: "lucia@test.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "u2",
    username: "Juan",
    email: "juan@test.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "u3",
    username: "Pedro",
    email: "pedro@test.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: true,
    lastSeenAt: "2026-06-20T15:00:00Z",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-20T15:00:00Z",
  },
  {
    id: "u4",
    username: "Ana",
    email: "ana@test.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "me",
    username: "Artur",
    email: "artur@test.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
];

export const currentUserId = "me";

// ─── Mock Channels ───────────────────────────────────────────
export const mockChannels: Channel[] = [
  {
    id: "ch1",
    name: "General",
    description: "Chat general del equipo. Para temas importantes y anuncios.",
    type: "PUBLIC",
    owner: { id: "u1", username: "Lucía" },
    membersCount: 24,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
  },
  {
    id: "ch2",
    name: "Diseño",
    description: "Discusiones de diseño UI/UX, feedback y brainstorming.",
    type: "PUBLIC",
    owner: { id: "u2", username: "Juan" },
    membersCount: 12,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
  },
  {
    id: "ch3",
    name: "Desarrollo",
    description: "Código, PRs, bugs y arquitectura técnica.",
    type: "PUBLIC",
    owner: { id: "u4", username: "Ana" },
    membersCount: 18,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
  },
  {
    id: "ch4",
    name: "Random",
    description: "Off-topic, memes y charla casual.",
    type: "PUBLIC",
    owner: { id: "u1", username: "Lucía" },
    membersCount: 30,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
  },
  {
    id: "ch5",
    name: "Marketing",
    description: "Estrategia de contenido, campañas y métricas.",
    type: "PRIVATE",
    owner: { id: "u2", username: "Juan" },
    membersCount: 6,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
  },
];

// ─── Memberships (which channels the current user belongs to) ─
export const mockMemberships = ["ch1", "ch2", "ch4"];

// ─── Mock Members per channel ────────────────────────────────
export const mockMembers: Record<string, ChannelMember[]> = {
  ch1: [
    { id: "m1", user: { id: "u1", username: "Lucía", email: "lucia@test.com", avatarUrl: null, isOnline: true }, role: "OWNER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m2", user: { id: "u2", username: "Juan", email: "juan@test.com", avatarUrl: null, isOnline: true }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m3", user: { id: "u3", username: "Pedro", email: "pedro@test.com", avatarUrl: null, isOnline: false }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m4", user: { id: "u4", username: "Ana", email: "ana@test.com", avatarUrl: null, isOnline: true }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m5", user: { id: "me", username: "Artur", email: "artur@test.com", avatarUrl: null, isOnline: true }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
  ],
  ch2: [
    { id: "m6", user: { id: "u2", username: "Juan", email: "juan@test.com", avatarUrl: null, isOnline: true }, role: "OWNER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m7", user: { id: "me", username: "Artur", email: "artur@test.com", avatarUrl: null, isOnline: true }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
  ],
  ch4: [
    { id: "m8", user: { id: "u1", username: "Lucía", email: "lucia@test.com", avatarUrl: null, isOnline: true }, role: "OWNER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m9", user: { id: "me", username: "Artur", email: "artur@test.com", avatarUrl: null, isOnline: true }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
    { id: "m10", user: { id: "u3", username: "Pedro", email: "pedro@test.com", avatarUrl: null, isOnline: false }, role: "MEMBER", joinedAt: "2026-01-01T00:00:00Z" },
  ],
};

// ─── Mock Messages per channel ───────────────────────────────
export const mockMessages: Record<string, Message[]> = {
  ch1: [
    {
      id: "msg1",
      content: "¡Buenos días equipo! Hoy tenemos reunión a las 11am.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch1", name: "General" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:00:00Z",
      updatedAt: "2026-06-21T09:00:00Z",
    },
    {
      id: "msg2",
      content: "Perfecto, voy a preparar la presentación.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch1", name: "General" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:05:00Z",
      updatedAt: "2026-06-21T09:05:00Z",
    },
    {
      id: "msg3",
      content: "Yo también estaré allí. ¿Comparto el enlace?",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch1", name: "General" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:10:00Z",
      updatedAt: "2026-06-21T09:10:00Z",
    },
    {
      id: "msg4",
      content: "Sí, porfa. Lo pongo en el calendario.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch1", name: "General" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:12:00Z",
      updatedAt: "2026-06-21T09:12:00Z",
    },
    {
      id: "msg5",
      content: "Listo, ya lo compartí en el canal.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch1", name: "General" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:15:00Z",
      updatedAt: "2026-06-21T09:15:00Z",
    },
  ],
  ch2: [
    {
      id: "msg6",
      content: "¿Qué les parece este nuevo mockup para la landing?",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch2", name: "Diseño" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T14:00:00Z",
      updatedAt: "2026-06-20T14:00:00Z",
    },
    {
      id: "msg7",
      content: "Me gusta! Los colores están muy bien balanceados.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch2", name: "Diseño" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T14:30:00Z",
      updatedAt: "2026-06-20T14:30:00Z",
    },
    {
      id: "msg8",
      content: "Podríamos ajustar el padding del hero.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch2", name: "Diseño" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T15:00:00Z",
      updatedAt: "2026-06-20T15:00:00Z",
    },
  ],
  ch4: [
    {
      id: "msg9",
      content: "Alguien juega Valorant después del trabajo?",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch4", name: "Random" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T18:00:00Z",
      updatedAt: "2026-06-19T18:00:00Z",
    },
    {
      id: "msg10",
      content: "Yo! Te escribo luego.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch4", name: "Random" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T18:15:00Z",
      updatedAt: "2026-06-19T18:15:00Z",
    },
  ],
  ch3: [
    {
      id: "msg11",
      content: "Chicos, el PR de la API de usuarios ya está listo para review.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T10:00:00Z",
      updatedAt: "2026-06-21T10:00:00Z",
    },
    {
      id: "msg12",
      content: "Dale, lo reviso hoy a la tarde.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T10:15:00Z",
      updatedAt: "2026-06-21T10:15:00Z",
    },
    {
      id: "msg13",
      content: "Agregué tests de integración para el módulo de auth.",
      author: { id: "u9", username: "Valentina", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T11:00:00Z",
      updatedAt: "2026-06-21T11:00:00Z",
    },
    {
      id: "msg14",
      content: "Buen trabajo Valen. Necesitamos cubrir más edge cases.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T11:30:00Z",
      updatedAt: "2026-06-21T11:30:00Z",
    },
    {
      id: "msg15",
      content: "Estuve viendo la lambda de notificaciones, está haciendo timeout.",
      author: { id: "u14", username: "Fernando", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T14:00:00Z",
      updatedAt: "2026-06-21T14:00:00Z",
    },
    {
      id: "msg16",
      content: "Lo sé, estoy trabajando en eso. Aumento el timeout a 30s.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T14:05:00Z",
      updatedAt: "2026-06-21T14:05:00Z",
    },
    {
      id: "msg17",
      content: "Aumentar el timeout no arregla el problema de fondo.",
      author: { id: "u9", username: "Valentina", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T14:10:00Z",
      updatedAt: "2026-06-21T14:10:00Z",
    },
    {
      id: "msg18",
      content: "Tiene razón Valen, mejor revisamos la query a la DB.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T14:30:00Z",
      updatedAt: "2026-06-21T14:30:00Z",
    },
    {
      id: "msg19",
      content: "La db está lenta porque falta un índice en la tabla de logs.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T15:00:00Z",
      updatedAt: "2026-06-21T15:00:00Z",
    },
    {
      id: "msg20",
      content: "Creo el índice ya. Buena atrapada Ana.",
      author: { id: "u14", username: "Fernando", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T15:05:00Z",
      updatedAt: "2026-06-21T15:05:00Z",
    },
    {
      id: "msg21",
      content: "¿Alguien ya revisó el PR de refactor del frontend?",
      author: { id: "u9", username: "Valentina", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-22T09:00:00Z",
      updatedAt: "2026-06-22T09:00:00Z",
    },
    {
      id: "msg22",
      content: "Yo lo vi, está clean. Solo un par de comments nomas.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-22T09:30:00Z",
      updatedAt: "2026-06-22T09:30:00Z",
    },
    {
      id: "msg23",
      content: "Ya subí la nueva versión del esquema de Prisma.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-22T10:00:00Z",
      updatedAt: "2026-06-22T10:00:00Z",
    },
    {
      id: "msg24",
      content: "Corrí la migración en staging y todo ok.",
      author: { id: "u14", username: "Fernando", avatarUrl: null },
      channel: { id: "ch3", name: "Desarrollo" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-22T11:00:00Z",
      updatedAt: "2026-06-22T11:00:00Z",
    },
  ],
  ch5: [
    {
      id: "msg25",
      content: "La campaña de junio está lista para revisión.",
      author: { id: "u15", username: "Laura", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T09:00:00Z",
      updatedAt: "2026-06-20T09:00:00Z",
    },
    {
      id: "msg26",
      content: "Perfecto Laura, la revisamos hoy.",
      author: { id: "u7", username: "Sofía", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T09:30:00Z",
      updatedAt: "2026-06-20T09:30:00Z",
    },
    {
      id: "msg27",
      content: "Los CTR están subiendo gracias al nuevo copy.",
      author: { id: "u15", username: "Laura", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T10:00:00Z",
      updatedAt: "2026-06-20T10:00:00Z",
    },
    {
      id: "msg28",
      content: "Necesitamos más alcance en LinkedIn.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T10:30:00Z",
      updatedAt: "2026-06-20T10:30:00Z",
    },
    {
      id: "msg29",
      content: "Podríamos probar con ads segmentados por industria.",
      author: { id: "u7", username: "Sofía", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T11:00:00Z",
      updatedAt: "2026-06-20T11:00:00Z",
    },
    {
      id: "msg30",
      content: "Buena idea. Preparo una propuesta para la próxima semana.",
      author: { id: "u15", username: "Laura", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T11:30:00Z",
      updatedAt: "2026-06-20T11:30:00Z",
    },
    {
      id: "msg31",
      content: "El newsletter de esta semana tiene 45% de open rate.",
      author: { id: "u7", username: "Sofía", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:00:00Z",
      updatedAt: "2026-06-21T09:00:00Z",
    },
    {
      id: "msg32",
      content: "Excelente! Vamos por el 50% la próxima.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T09:15:00Z",
      updatedAt: "2026-06-21T09:15:00Z",
    },
    {
      id: "msg33",
      content: "Ya hablé con diseño para los nuevos banners.",
      author: { id: "u15", username: "Laura", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T10:00:00Z",
      updatedAt: "2026-06-21T10:00:00Z",
    },
    {
      id: "msg34",
      content: "Perfecto. Les comparto los briefs por acá.",
      author: { id: "u7", username: "Sofía", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T10:30:00Z",
      updatedAt: "2026-06-21T10:30:00Z",
    },
    {
      id: "msg35",
      content: "La competencia lanzó una campaña similar, hay que diferenciarnos.",
      author: { id: "u15", username: "Laura", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T11:00:00Z",
      updatedAt: "2026-06-21T11:00:00Z",
    },
    {
      id: "msg36",
      content: "Ya vi. Nuestro valor agregado es el soporte personalizado.",
      author: { id: "u2", username: "Juan", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T11:15:00Z",
      updatedAt: "2026-06-21T11:15:00Z",
    },
    {
      id: "msg37",
      content: "Exacto. Destaquemos eso en la próxima newsletter.",
      author: { id: "u7", username: "Sofía", avatarUrl: null },
      channel: { id: "ch5", name: "Marketing" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-21T11:30:00Z",
      updatedAt: "2026-06-21T11:30:00Z",
    },
  ],
  ch6: [
    {
      id: "msg38",
      content: "La migración a la nueva DB está lista para staging.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T09:00:00Z",
      updatedAt: "2026-06-19T09:00:00Z",
    },
    {
      id: "msg39",
      content: "Ya revisé el script, todo en orden.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T09:30:00Z",
      updatedAt: "2026-06-19T09:30:00Z",
    },
    {
      id: "msg40",
      content: "Podemos hacer el deploy esta noche sin impacto.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T10:00:00Z",
      updatedAt: "2026-06-19T10:00:00Z",
    },
    {
      id: "msg41",
      content: "La api de websockets necesita reconexión automática.",
      author: { id: "u9", username: "Valentina", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T11:00:00Z",
      updatedAt: "2026-06-19T11:00:00Z",
    },
    {
      id: "msg42",
      content: "cierto, lo agregué al backlog del sprint.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T11:30:00Z",
      updatedAt: "2026-06-19T11:30:00Z",
    },
    {
      id: "msg43",
      content: "El cache de Redis se está llenando muy rápido.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T09:00:00Z",
      updatedAt: "2026-06-20T09:00:00Z",
    },
    {
      id: "msg44",
      content: "Hay que ajustar el TTL de las sesiones.",
      author: { id: "me", username: "Artur", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T09:30:00Z",
      updatedAt: "2026-06-20T09:30:00Z",
    },
    {
      id: "msg45",
      content: "Ya lo bajé a 30 minutos. Vamos a monitorizar.",
      author: { id: "u4", username: "Ana", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T10:00:00Z",
      updatedAt: "2026-06-20T10:00:00Z",
    },
    {
      id: "msg46",
      content: "La tasa de errores 500 bajó un 80% con el último fix.",
      author: { id: "u9", username: "Valentina", avatarUrl: null },
      channel: { id: "ch6", name: "Backend" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-20T14:00:00Z",
      updatedAt: "2026-06-20T14:00:00Z",
    },
  ],
  ch7: [
    {
      id: "msg47",
      content: "Recordatorio: la evaluación de performance cierra el viernes.",
      author: { id: "u11", username: "Camila", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T09:00:00Z",
      updatedAt: "2026-06-18T09:00:00Z",
    },
    {
      id: "msg48",
      content: "Gracias Cami, las estoy terminando.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T09:30:00Z",
      updatedAt: "2026-06-18T09:30:00Z",
    },
    {
      id: "msg49",
      content: "El nuevo beneficio de días flexibles ya está aprobado.",
      author: { id: "u11", username: "Camila", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T10:00:00Z",
      updatedAt: "2026-06-18T10:00:00Z",
    },
    {
      id: "msg50",
      content: "Genial! Eso va a mejorar el clima laboral.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T10:30:00Z",
      updatedAt: "2026-06-18T10:30:00Z",
    },
    {
      id: "msg51",
      content: "Necesito que suban las hojas de ruta actualizadas.",
      author: { id: "u11", username: "Camila", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T11:00:00Z",
      updatedAt: "2026-06-18T11:00:00Z",
    },
    {
      id: "msg52",
      content: "Las subo mañana sin falta.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-18T11:30:00Z",
      updatedAt: "2026-06-18T11:30:00Z",
    },
    {
      id: "msg53",
      content: "La encuesta de satisfacción tuvo 92% de participación.",
      author: { id: "u11", username: "Camila", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T09:00:00Z",
      updatedAt: "2026-06-19T09:00:00Z",
    },
    {
      id: "msg54",
      content: "Muy buen número! Vamos a compartir los resultados en la weekly.",
      author: { id: "u1", username: "Lucía", avatarUrl: null },
      channel: { id: "ch7", name: "Recursos Humanos" },
      replyTo: null,
      readBy: [],
      createdAt: "2026-06-19T09:30:00Z",
      updatedAt: "2026-06-19T09:30:00Z",
    },
  ],
};

// ─── Unread counts per channel ───────────────────────────────
export const mockUnreadCounts: Record<string, number> = {
  ch1: 3,
  ch2: 1,
  ch4: 0,
};

// ─── Helper: initials from username ──────────────────────────
export function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}
