import type { AdminUser, DayActivity, AdminChannel } from "@/modules/admin/interfaces/admin.interface";

// ─── Admin Users (15 users) ────────────────────────────────
export const mockAdminUsers: AdminUser[] = [
  {
    id: "me",
    username: "Artur",
    email: "artur@azac.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-11-01T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 847,
    lastActiveChannel: "General",
    isSuspended: false,
    twoFactorEnabled: true,
  },
  {
    id: "u1",
    username: "Lucía",
    email: "lucia@azac.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-11-02T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 1203,
    lastActiveChannel: "General",
    isSuspended: false,
    twoFactorEnabled: true,
  },
  {
    id: "u2",
    username: "Juan",
    email: "juan@azac.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-11-05T00:00:00Z",
    updatedAt: "2026-06-24T00:00:00Z",
    messageCount: 654,
    lastActiveChannel: "Diseño",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u3",
    username: "Pedro",
    email: "pedro@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: true,
    lastSeenAt: "2026-06-20T15:00:00Z",
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2026-06-20T15:00:00Z",
    messageCount: 234,
    lastActiveChannel: "General",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u4",
    username: "Ana",
    email: "ana@azac.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 912,
    lastActiveChannel: "Diseño",
    isSuspended: false,
    twoFactorEnabled: true,
  },
  {
    id: "u5",
    username: "María",
    email: "maria@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 189,
    lastActiveChannel: "Random",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u6",
    username: "Carlos",
    email: "carlos@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: false,
    lastSeenAt: "2026-06-18T10:00:00Z",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-06-18T10:00:00Z",
    messageCount: 56,
    lastActiveChannel: null,
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u7",
    username: "Sofía",
    email: "sofia@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 445,
    lastActiveChannel: "Marketing",
    isSuspended: false,
    twoFactorEnabled: true,
  },
  {
    id: "u8",
    username: "Diego",
    email: "diego@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: true,
    lastSeenAt: "2026-06-23T18:30:00Z",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-06-23T18:30:00Z",
    messageCount: 312,
    lastActiveChannel: "Desarrollo",
    isSuspended: true,
    twoFactorEnabled: false,
  },
  {
    id: "u9",
    username: "Valentina",
    email: "valentina@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 567,
    lastActiveChannel: "General",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u10",
    username: "Miguel",
    email: "miguel@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: true,
    lastSeenAt: "2026-06-22T09:00:00Z",
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-06-22T09:00:00Z",
    messageCount: 98,
    lastActiveChannel: null,
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u11",
    username: "Camila",
    email: "camila@azac.com",
    avatarUrl: null,
    role: "ADMIN",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2025-11-03T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 1567,
    lastActiveChannel: "General",
    isSuspended: false,
    twoFactorEnabled: true,
  },
  {
    id: "u12",
    username: "Andrés",
    email: "andres@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: false,
    lastSeenAt: "2026-06-10T14:00:00Z",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-06-10T14:00:00Z",
    messageCount: 12,
    lastActiveChannel: null,
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u13",
    username: "Gabriela",
    email: "gabriela@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-02-14T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 278,
    lastActiveChannel: "Random",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u14",
    username: "Fernando",
    email: "fernando@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: false,
    isEmailVerified: true,
    lastSeenAt: "2026-06-19T11:00:00Z",
    createdAt: "2026-03-20T00:00:00Z",
    updatedAt: "2026-06-19T11:00:00Z",
    messageCount: 134,
    lastActiveChannel: "Desarrollo",
    isSuspended: false,
    twoFactorEnabled: false,
  },
  {
    id: "u15",
    username: "Laura",
    email: "laura@azac.com",
    avatarUrl: null,
    role: "USER",
    isOnline: true,
    isEmailVerified: true,
    lastSeenAt: null,
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
    messageCount: 389,
    lastActiveChannel: "Marketing",
    isSuspended: false,
    twoFactorEnabled: false,
  },
];

// ─── Activity data per user (messages by day of week) ──────
export const mockUserActivity: Record<string, DayActivity[]> = {
  me: [
    { day: "Lun", fullDay: "Lunes", messages: 24 },
    { day: "Mar", fullDay: "Martes", messages: 18 },
    { day: "Mié", fullDay: "Miércoles", messages: 31 },
    { day: "Jue", fullDay: "Jueves", messages: 12 },
    { day: "Vie", fullDay: "Viernes", messages: 27 },
    { day: "Sáb", fullDay: "Sábado", messages: 5 },
    { day: "Dom", fullDay: "Domingo", messages: 3 },
  ],
  u1: [
    { day: "Lun", fullDay: "Lunes", messages: 35 },
    { day: "Mar", fullDay: "Martes", messages: 28 },
    { day: "Mié", fullDay: "Miércoles", messages: 42 },
    { day: "Jue", fullDay: "Jueves", messages: 20 },
    { day: "Vie", fullDay: "Viernes", messages: 38 },
    { day: "Sáb", fullDay: "Sábado", messages: 8 },
    { day: "Dom", fullDay: "Domingo", messages: 2 },
  ],
  u2: [
    { day: "Lun", fullDay: "Lunes", messages: 15 },
    { day: "Mar", fullDay: "Martes", messages: 22 },
    { day: "Mié", fullDay: "Miércoles", messages: 18 },
    { day: "Jue", fullDay: "Jueves", messages: 30 },
    { day: "Vie", fullDay: "Viernes", messages: 14 },
    { day: "Sáb", fullDay: "Sábado", messages: 4 },
    { day: "Dom", fullDay: "Domingo", messages: 1 },
  ],
  u3: [
    { day: "Lun", fullDay: "Lunes", messages: 8 },
    { day: "Mar", fullDay: "Martes", messages: 5 },
    { day: "Mié", fullDay: "Miércoles", messages: 12 },
    { day: "Jue", fullDay: "Jueves", messages: 7 },
    { day: "Vie", fullDay: "Viernes", messages: 10 },
    { day: "Sáb", fullDay: "Sábado", messages: 2 },
    { day: "Dom", fullDay: "Domingo", messages: 0 },
  ],
  u4: [
    { day: "Lun", fullDay: "Lunes", messages: 28 },
    { day: "Mar", fullDay: "Martes", messages: 32 },
    { day: "Mié", fullDay: "Miércoles", messages: 25 },
    { day: "Jue", fullDay: "Jueves", messages: 19 },
    { day: "Vie", fullDay: "Viernes", messages: 33 },
    { day: "Sáb", fullDay: "Sábado", messages: 6 },
    { day: "Dom", fullDay: "Domingo", messages: 4 },
  ],
  u5: [
    { day: "Lun", fullDay: "Lunes", messages: 5 },
    { day: "Mar", fullDay: "Martes", messages: 8 },
    { day: "Mié", fullDay: "Miércoles", messages: 6 },
    { day: "Jue", fullDay: "Jueves", messages: 11 },
    { day: "Vie", fullDay: "Viernes", messages: 7 },
    { day: "Sáb", fullDay: "Sábado", messages: 3 },
    { day: "Dom", fullDay: "Domingo", messages: 1 },
  ],
  u7: [
    { day: "Lun", fullDay: "Lunes", messages: 12 },
    { day: "Mar", fullDay: "Martes", messages: 15 },
    { day: "Mié", fullDay: "Miércoles", messages: 10 },
    { day: "Jue", fullDay: "Jueves", messages: 18 },
    { day: "Vie", fullDay: "Viernes", messages: 14 },
    { day: "Sáb", fullDay: "Sábado", messages: 2 },
    { day: "Dom", fullDay: "Domingo", messages: 0 },
  ],
  u9: [
    { day: "Lun", fullDay: "Lunes", messages: 20 },
    { day: "Mar", fullDay: "Martes", messages: 16 },
    { day: "Mié", fullDay: "Miércoles", messages: 22 },
    { day: "Jue", fullDay: "Jueves", messages: 14 },
    { day: "Vie", fullDay: "Viernes", messages: 19 },
    { day: "Sáb", fullDay: "Sábado", messages: 5 },
    { day: "Dom", fullDay: "Domingo", messages: 2 },
  ],
  u11: [
    { day: "Lun", fullDay: "Lunes", messages: 40 },
    { day: "Mar", fullDay: "Martes", messages: 35 },
    { day: "Mié", fullDay: "Miércoles", messages: 48 },
    { day: "Jue", fullDay: "Jueves", messages: 32 },
    { day: "Vie", fullDay: "Viernes", messages: 45 },
    { day: "Sáb", fullDay: "Sábado", messages: 10 },
    { day: "Dom", fullDay: "Domingo", messages: 6 },
  ],
  u15: [
    { day: "Lun", fullDay: "Lunes", messages: 10 },
    { day: "Mar", fullDay: "Martes", messages: 14 },
    { day: "Mié", fullDay: "Miércoles", messages: 8 },
    { day: "Jue", fullDay: "Jueves", messages: 16 },
    { day: "Vie", fullDay: "Viernes", messages: 11 },
    { day: "Sáb", fullDay: "Sábado", messages: 1 },
    { day: "Dom", fullDay: "Domingo", messages: 0 },
  ],
};

// ─── Default activity for users without specific data ──────
export const getDefaultActivity = (): DayActivity[] => [
  { day: "Lun", fullDay: "Lunes", messages: 0 },
  { day: "Mar", fullDay: "Martes", messages: 0 },
  { day: "Mié", fullDay: "Miércoles", messages: 0 },
  { day: "Jue", fullDay: "Jueves", messages: 0 },
  { day: "Vie", fullDay: "Viernes", messages: 0 },
  { day: "Sáb", fullDay: "Sábado", messages: 0 },
  { day: "Dom", fullDay: "Domingo", messages: 0 },
];

// ─── Admin Channels (enriched) ──────────────────────────────
export const mockAdminChannels: AdminChannel[] = [
  {
    id: "ch1",
    name: "General",
    description: "Chat general del equipo. Para temas importantes y anuncios.",
    type: "PUBLIC",
    owner: { id: "u1", username: "Lucía" },
    membersCount: 24,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
    creator: { id: "u1", username: "Lucía" },
    memberList: [
      { id: "u1", username: "Lucía", role: "OWNER" },
      { id: "u2", username: "Juan", role: "MEMBER" },
      { id: "u3", username: "Pedro", role: "MEMBER" },
      { id: "u4", username: "Ana", role: "MEMBER" },
      { id: "me", username: "Artur", role: "MEMBER" },
    ],
  },
  {
    id: "ch2",
    name: "Diseño",
    description: "Discusiones de diseño UI/UX, feedback y brainstorming.",
    type: "PUBLIC",
    owner: { id: "u2", username: "Juan" },
    membersCount: 12,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
    creator: { id: "u2", username: "Juan" },
    memberList: [
      { id: "u2", username: "Juan", role: "OWNER" },
      { id: "me", username: "Artur", role: "MEMBER" },
      { id: "u4", username: "Ana", role: "MEMBER" },
      { id: "u7", username: "Sofía", role: "MEMBER" },
      { id: "u15", username: "Laura", role: "MEMBER" },
    ],
  },
  {
    id: "ch3",
    name: "Desarrollo",
    description: "Código, PRs, bugs y arquitectura técnica.",
    type: "PUBLIC",
    owner: { id: "u4", username: "Ana" },
    membersCount: 18,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
    creator: { id: "u4", username: "Ana" },
    memberList: [
      { id: "u4", username: "Ana", role: "OWNER" },
      { id: "u2", username: "Juan", role: "MEMBER" },
      { id: "u9", username: "Valentina", role: "MEMBER" },
      { id: "u14", username: "Fernando", role: "MEMBER" },
    ],
  },
  {
    id: "ch4",
    name: "Random",
    description: "Off-topic, memes y charla casual.",
    type: "PUBLIC",
    owner: { id: "u1", username: "Lucía" },
    membersCount: 30,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
    creator: { id: "u1", username: "Lucía" },
    memberList: [
      { id: "u1", username: "Lucía", role: "OWNER" },
      { id: "me", username: "Artur", role: "MEMBER" },
      { id: "u3", username: "Pedro", role: "MEMBER" },
      { id: "u5", username: "María", role: "MEMBER" },
      { id: "u13", username: "Gabriela", role: "MEMBER" },
    ],
  },
  {
    id: "ch5",
    name: "Marketing",
    description: "Estrategia de contenido, campañas y métricas.",
    type: "PRIVATE",
    owner: { id: "u2", username: "Juan" },
    membersCount: 6,
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-06-21T00:00:00Z",
    creator: { id: "u2", username: "Juan" },
    memberList: [
      { id: "u2", username: "Juan", role: "OWNER" },
      { id: "u7", username: "Sofía", role: "MEMBER" },
      { id: "u15", username: "Laura", role: "MEMBER" },
    ],
  },
  {
    id: "ch6",
    name: "Backend",
    description: "APIs, base de datos, infraestructura y despliegues.",
    type: "PUBLIC",
    owner: { id: "me", username: "Artur" },
    membersCount: 8,
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-06-20T00:00:00Z",
    creator: { id: "me", username: "Artur" },
    memberList: [
      { id: "me", username: "Artur", role: "OWNER" },
      { id: "u4", username: "Ana", role: "MEMBER" },
      { id: "u9", username: "Valentina", role: "MEMBER" },
    ],
  },
  {
    id: "ch7",
    name: "Recursos Humanos",
    description: "Procesos internos, contrataciones y bienestar.",
    type: "PRIVATE",
    owner: { id: "u11", username: "Camila" },
    membersCount: 4,
    createdAt: "2026-03-01T00:00:00Z",
    updatedAt: "2026-06-18T00:00:00Z",
    creator: { id: "u11", username: "Camila" },
    memberList: [
      { id: "u11", username: "Camila", role: "OWNER" },
      { id: "u1", username: "Lucía", role: "MEMBER" },
    ],
  },
];

// ─── User channel participation ─────────────────────────────
export const mockUserChannels: Record<string, Array<{ id: string; name: string; role: "OWNER" | "MEMBER" | "GUEST" }>> = {
  me: [
    { id: "ch1", name: "General", role: "MEMBER" },
    { id: "ch2", name: "Diseño", role: "MEMBER" },
    { id: "ch4", name: "Random", role: "MEMBER" },
    { id: "ch6", name: "Backend", role: "OWNER" },
  ],
  u1: [
    { id: "ch1", name: "General", role: "OWNER" },
    { id: "ch4", name: "Random", role: "OWNER" },
    { id: "ch5", name: "Marketing", role: "MEMBER" },
  ],
  u2: [
    { id: "ch1", name: "General", role: "MEMBER" },
    { id: "ch2", name: "Diseño", role: "OWNER" },
    { id: "ch3", name: "Desarrollo", role: "MEMBER" },
    { id: "ch5", name: "Marketing", role: "OWNER" },
  ],
  u3: [
    { id: "ch1", name: "General", role: "MEMBER" },
    { id: "ch4", name: "Random", role: "MEMBER" },
  ],
  u4: [
    { id: "ch1", name: "General", role: "MEMBER" },
    { id: "ch2", name: "Diseño", role: "MEMBER" },
    { id: "ch3", name: "Desarrollo", role: "OWNER" },
    { id: "ch6", name: "Backend", role: "MEMBER" },
  ],
  u5: [
    { id: "ch4", name: "Random", role: "MEMBER" },
    { id: "ch2", name: "Diseño", role: "MEMBER" },
  ],
  u7: [
    { id: "ch2", name: "Diseño", role: "MEMBER" },
    { id: "ch5", name: "Marketing", role: "MEMBER" },
  ],
  u9: [
    { id: "ch3", name: "Desarrollo", role: "MEMBER" },
    { id: "ch6", name: "Backend", role: "MEMBER" },
    { id: "ch1", name: "General", role: "MEMBER" },
  ],
  u11: [
    { id: "ch7", name: "Recursos Humanos", role: "OWNER" },
    { id: "ch1", name: "General", role: "MEMBER" },
  ],
  u15: [
    { id: "ch2", name: "Diseño", role: "MEMBER" },
    { id: "ch5", name: "Marketing", role: "MEMBER" },
  ],
  u13: [
    { id: "ch4", name: "Random", role: "MEMBER" },
  ],
  u14: [
    { id: "ch3", name: "Desarrollo", role: "MEMBER" },
  ],
};

// ─── Helpers ─────────────────────────────────────────────────
export function getAdminUserById(id: string): AdminUser | undefined {
  return mockAdminUsers.find((u) => u.id === id);
}

export function getActivityByUserId(userId: string): DayActivity[] {
  return mockUserActivity[userId] ?? getDefaultActivity();
}

export function getUserChannels(userId: string): Array<{ id: string; name: string; role: "OWNER" | "MEMBER" | "GUEST" }> {
  return mockUserChannels[userId] ?? [];
}

export function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}

export function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("es-ES", {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

export function formatDateTime(dateStr: string | null): string {
  if (!dateStr) return "-";
  const date = new Date(dateStr);
  return date.toLocaleDateString("es-ES", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
